### ISSUE TITLE
How do I scroll with Trackman Marble?

### ISSUE THREAD

**Issue by KillyMXI** [spitfirex86/TBScroll#1]
Logitech Trackman Marble doesn't have the middle button.
Extra buttons are for Back and Forward actions.

My XMBC config is as follows:

- Back - toggle scroll (I've been using "hold to scroll" for a while, but the button is not very ergonomic to hold for a long time);
- Forward - mapped to middle button.

Prior to this I've had following configuration:

- RMB click - mapped to RMB click;
- RMB hold and ball move - scroll;
- Back - mapped to middle button.

It was more ergonomic but I'm tired of managing exceptions for apps where it is not suitable.

By the way, I always limit scroll to vertical direction.
When I need the horizontal scroll - I'd much prefer it to be activated differently. Nothing worse than unintended horizontal scroll or fighting with imperfect scroll direction detection.

**Comment by spitfirex86** [comment]
Any button that's mapped to MMB should trigger scrolling. Based on your settings this would be the Forward button. 

The sensitivity setting also doubles as a deadzone because of how it's implemented. For the horizontal sensitivity, I personally use a value 6x greater than vertical sensitivity and I don't have any issues with accidental scrolling. You can probably set it even higher since Windows expects the horizontal scroll to be "slower" anyway.

There is no "direction detection" here since both directions are processed at the same time and scroll events for each direction don't interrupt each other. So the only issue you can encounter is accidental scrolling in the other direction if the sensitivity values are too low. (lower numbers == higher sensitivity)

I'm pretty sure you can also Shift+VScroll to scroll horizontally in most apps, so if that's something you prefer you can disable horizontal scrolling completely by setting the horizontal sensitivity value really high so it never triggers.

**Comment by spitfirex86** [comment]
Possibly relevant: It is now also possible to explicitly choose one of the XButtons (back/forward) in the settings dialog for use as the scroll button.
